# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: WookieWeb
author: Andy Woo
email: wooandy@mac.com
description: > # this means to ignore newlines until "baseurl:"
  Roooarrgh ur roo. Crazylabel founder. Previously 6:700/275 and VR2ZBY. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wookieweb.com" # the base hostname & protocol for your site, e.g. http://example.com
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
logo: /assets/andy.jpg
twitter_username: _wooandy
instagram_username: _wooandy
github_username:  wooandy
rss: rss

show_excerpts: false # set to true to show excerpts on the homepage

# Build settings
markdown: kramdown
theme: minima
# theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  
permalink: /:year/:month/:day/:title:output_ext
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
